//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTS.Clock.Business.FeatureServices.AlmasSmsSoap {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.neginalmas.ir/", ConfigurationName="AlmasSmsSoap.AlmasSmsSoap")]
    public interface AlmasSmsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/SendSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long SendSms(out long[] pMessageIds, string pUsername, string pPassword, string[] messages, string[] mobiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/OneSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long OneSend(string pUsername, string pPassword, string message, string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetLastMessageId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetLastMessageId(string pUsername, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/OneReceive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OneReceive(string pUsername, string pPassword, string separator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/OneCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OneCredit(string pUsername, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/Send1Sms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long Send1Sms(out long pMessageId, string pUsername, string pPassword, string message, string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/SendSms2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long SendSms2(out long[] pMessageIds, string pUsername, string pPassword, string[] messages, string[] mobiles, string[] UDH, int[] encodings, int[] mclass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/SendSms3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long SendSms3(out GTS.Clock.Business.FeatureServices.AlmasSmsSoap.SendSmsResult result, string pUsername, string pPassword, string[] messages, string[] mobiles, string[] UDH, int[] encodings, int[] mclass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetMessageStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetMessageStatus(out int[] pStatuses, string pUsername, string pPassword, long[] pMessageIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetRealMessageStatuses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetRealMessageStatuses(out int[] pStatuses, string pUsername, string pPassword, long[] pMessageIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/SendSmsT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long SendSmsT(out long[] pMessageIds, string pTicket, string[] messages, string[] mobiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/SendSms2T", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long SendSms2T(out long[] pMessageIds, string pTicket, string[] messages, string[] mobiles, string[] UDH, int[] encodings, int[] mclass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/SendSms3T", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long SendSms3T(out GTS.Clock.Business.FeatureServices.AlmasSmsSoap.SendSmsResult result, string pTicket, string[] messages, string[] mobiles, string[] UDH, int[] encodings, int[] mclass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetMessageStatusT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetMessageStatusT(out int[] pStatuses, string pTicket, long[] pMessageIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetRealMessageStatusesT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetRealMessageStatusesT(out int[] pStatuses, string pTicket, long[] pMessageIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetCredit(out long pCredit, string pUsername, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetReceivedSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetReceivedSms(out string pRecieved, string pUsername, string pPassword, bool pWithSchema, bool mergeMessages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetReceivedSms2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetReceivedSms2(out string[] pMessages, out string[] pFroms, out string[] pSmsc, out string[] pMessageIds, out System.DateTime[] pEnteredDate, string pUsername, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetReceivedSms3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetReceivedSms3(out string[] pMessages, out string[] pFroms, out string[] pMessageIds, out System.DateTime[] pEnteredDate, string pUsername, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetReport(out System.Data.DataTable pReport, string pUsername, string pPassword, System.DateTime pStart, System.DateTime pEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetInfo(out string pSmsNumber, out long pCredit, out string pName, out int pRole, out int pUserId, string pUsername, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ChangePassword(string pUsername, string pPassword, string pNewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetSmsCost", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetSmsCost(out int cost, string pUsername, string pPassword, string sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/ContactInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ContactInsert(string pUsername, string pPassword, bool pIsLocked, long pCode, string pMobile, string pFirstName, string pLastName, string pNickName, string pEmail, string pAddress, string pPhone, bool pIsMan, string pVar1, string pVar2, string pDesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/ContactUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ContactUpdate(string pUsername, string pPassword, bool pIsLocked, long pCode, string pMobile, string pFirstName, string pLastName, string pNickName, string pEmail, string pAddress, string pPhone, bool pIsMan, string pVar1, string pVar2, string pDesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/ContactAddToGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ContactAddToGroup(string pUsername, string pPassword, long pContactCode, long pGroupCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/ContactFindByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ContactFindByCode(string pUsername, string pPassword, long pContactCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/ContactFindByMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ContactFindByMobile(string pUsername, string pPassword, string pMobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetAuthorizationTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAuthorizationTicket(string pUsername, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Logout(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetCreditT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetCreditT(out long pCredit, string pTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetReceivedSmsT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetReceivedSmsT(out string pRecieved, string pTicket, bool pWithSchema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetReceivedSms2T", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetReceivedSms2T(out string pRecieved, string pTicket, bool pWithSchema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetChargeInfoT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetChargeInfoT(out System.Data.DataTable pReport, string pTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetSmsCostT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetSmsCostT(out int cost, string pTicket, string sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetSmsNumberPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetSmsNumberPrice(string smsNumber, int basePrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetSmsNumberPrice2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetSmsNumberPrice2(string fixPart, string varPart, double ceilPrice, double floorPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.neginalmas.ir/GetSectionCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        byte GetSectionCount(string body);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.neginalmas.ir/")]
    public partial class SendSmsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long[] messageIdsField;
        
        private int sendIdField;
        
        private long sendCostField;
        
        private int smsCountField;
        
        private int receiversCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public long[] MessageIds {
            get {
                return this.messageIdsField;
            }
            set {
                this.messageIdsField = value;
                this.RaisePropertyChanged("MessageIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SendId {
            get {
                return this.sendIdField;
            }
            set {
                this.sendIdField = value;
                this.RaisePropertyChanged("SendId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long SendCost {
            get {
                return this.sendCostField;
            }
            set {
                this.sendCostField = value;
                this.RaisePropertyChanged("SendCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SmsCount {
            get {
                return this.smsCountField;
            }
            set {
                this.smsCountField = value;
                this.RaisePropertyChanged("SmsCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ReceiversCount {
            get {
                return this.receiversCountField;
            }
            set {
                this.receiversCountField = value;
                this.RaisePropertyChanged("ReceiversCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlmasSmsSoapChannel : GTS.Clock.Business.FeatureServices.AlmasSmsSoap.AlmasSmsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmasSmsSoapClient : System.ServiceModel.ClientBase<GTS.Clock.Business.FeatureServices.AlmasSmsSoap.AlmasSmsSoap>, GTS.Clock.Business.FeatureServices.AlmasSmsSoap.AlmasSmsSoap {
        
        public AlmasSmsSoapClient() {
        }
        
        public AlmasSmsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmasSmsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmasSmsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmasSmsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long SendSms(out long[] pMessageIds, string pUsername, string pPassword, string[] messages, string[] mobiles) {
            return base.Channel.SendSms(out pMessageIds, pUsername, pPassword, messages, mobiles);
        }
        
        public long OneSend(string pUsername, string pPassword, string message, string mobile) {
            return base.Channel.OneSend(pUsername, pPassword, message, mobile);
        }
        
        public long GetLastMessageId(string pUsername, string pPassword) {
            return base.Channel.GetLastMessageId(pUsername, pPassword);
        }
        
        public string OneReceive(string pUsername, string pPassword, string separator) {
            return base.Channel.OneReceive(pUsername, pPassword, separator);
        }
        
        public string OneCredit(string pUsername, string pPassword) {
            return base.Channel.OneCredit(pUsername, pPassword);
        }
        
        public long Send1Sms(out long pMessageId, string pUsername, string pPassword, string message, string mobile) {
            return base.Channel.Send1Sms(out pMessageId, pUsername, pPassword, message, mobile);
        }
        
        public long SendSms2(out long[] pMessageIds, string pUsername, string pPassword, string[] messages, string[] mobiles, string[] UDH, int[] encodings, int[] mclass) {
            return base.Channel.SendSms2(out pMessageIds, pUsername, pPassword, messages, mobiles, UDH, encodings, mclass);
        }
        
        public long SendSms3(out GTS.Clock.Business.FeatureServices.AlmasSmsSoap.SendSmsResult result, string pUsername, string pPassword, string[] messages, string[] mobiles, string[] UDH, int[] encodings, int[] mclass) {
            return base.Channel.SendSms3(out result, pUsername, pPassword, messages, mobiles, UDH, encodings, mclass);
        }
        
        public long GetMessageStatus(out int[] pStatuses, string pUsername, string pPassword, long[] pMessageIds) {
            return base.Channel.GetMessageStatus(out pStatuses, pUsername, pPassword, pMessageIds);
        }
        
        public long GetRealMessageStatuses(out int[] pStatuses, string pUsername, string pPassword, long[] pMessageIds) {
            return base.Channel.GetRealMessageStatuses(out pStatuses, pUsername, pPassword, pMessageIds);
        }
        
        public long SendSmsT(out long[] pMessageIds, string pTicket, string[] messages, string[] mobiles) {
            return base.Channel.SendSmsT(out pMessageIds, pTicket, messages, mobiles);
        }
        
        public long SendSms2T(out long[] pMessageIds, string pTicket, string[] messages, string[] mobiles, string[] UDH, int[] encodings, int[] mclass) {
            return base.Channel.SendSms2T(out pMessageIds, pTicket, messages, mobiles, UDH, encodings, mclass);
        }
        
        public long SendSms3T(out GTS.Clock.Business.FeatureServices.AlmasSmsSoap.SendSmsResult result, string pTicket, string[] messages, string[] mobiles, string[] UDH, int[] encodings, int[] mclass) {
            return base.Channel.SendSms3T(out result, pTicket, messages, mobiles, UDH, encodings, mclass);
        }
        
        public long GetMessageStatusT(out int[] pStatuses, string pTicket, long[] pMessageIds) {
            return base.Channel.GetMessageStatusT(out pStatuses, pTicket, pMessageIds);
        }
        
        public long GetRealMessageStatusesT(out int[] pStatuses, string pTicket, long[] pMessageIds) {
            return base.Channel.GetRealMessageStatusesT(out pStatuses, pTicket, pMessageIds);
        }
        
        public long GetCredit(out long pCredit, string pUsername, string pPassword) {
            return base.Channel.GetCredit(out pCredit, pUsername, pPassword);
        }
        
        public long GetReceivedSms(out string pRecieved, string pUsername, string pPassword, bool pWithSchema, bool mergeMessages) {
            return base.Channel.GetReceivedSms(out pRecieved, pUsername, pPassword, pWithSchema, mergeMessages);
        }
        
        public long GetReceivedSms2(out string[] pMessages, out string[] pFroms, out string[] pSmsc, out string[] pMessageIds, out System.DateTime[] pEnteredDate, string pUsername, string pPassword) {
            return base.Channel.GetReceivedSms2(out pMessages, out pFroms, out pSmsc, out pMessageIds, out pEnteredDate, pUsername, pPassword);
        }
        
        public long GetReceivedSms3(out string[] pMessages, out string[] pFroms, out string[] pMessageIds, out System.DateTime[] pEnteredDate, string pUsername, string pPassword) {
            return base.Channel.GetReceivedSms3(out pMessages, out pFroms, out pMessageIds, out pEnteredDate, pUsername, pPassword);
        }
        
        public int GetReport(out System.Data.DataTable pReport, string pUsername, string pPassword, System.DateTime pStart, System.DateTime pEnd) {
            return base.Channel.GetReport(out pReport, pUsername, pPassword, pStart, pEnd);
        }
        
        public int GetInfo(out string pSmsNumber, out long pCredit, out string pName, out int pRole, out int pUserId, string pUsername, string pPassword) {
            return base.Channel.GetInfo(out pSmsNumber, out pCredit, out pName, out pRole, out pUserId, pUsername, pPassword);
        }
        
        public int ChangePassword(string pUsername, string pPassword, string pNewPassword) {
            return base.Channel.ChangePassword(pUsername, pPassword, pNewPassword);
        }
        
        public int GetSmsCost(out int cost, string pUsername, string pPassword, string sms) {
            return base.Channel.GetSmsCost(out cost, pUsername, pPassword, sms);
        }
        
        public int ContactInsert(string pUsername, string pPassword, bool pIsLocked, long pCode, string pMobile, string pFirstName, string pLastName, string pNickName, string pEmail, string pAddress, string pPhone, bool pIsMan, string pVar1, string pVar2, string pDesc) {
            return base.Channel.ContactInsert(pUsername, pPassword, pIsLocked, pCode, pMobile, pFirstName, pLastName, pNickName, pEmail, pAddress, pPhone, pIsMan, pVar1, pVar2, pDesc);
        }
        
        public int ContactUpdate(string pUsername, string pPassword, bool pIsLocked, long pCode, string pMobile, string pFirstName, string pLastName, string pNickName, string pEmail, string pAddress, string pPhone, bool pIsMan, string pVar1, string pVar2, string pDesc) {
            return base.Channel.ContactUpdate(pUsername, pPassword, pIsLocked, pCode, pMobile, pFirstName, pLastName, pNickName, pEmail, pAddress, pPhone, pIsMan, pVar1, pVar2, pDesc);
        }
        
        public int ContactAddToGroup(string pUsername, string pPassword, long pContactCode, long pGroupCode) {
            return base.Channel.ContactAddToGroup(pUsername, pPassword, pContactCode, pGroupCode);
        }
        
        public string ContactFindByCode(string pUsername, string pPassword, long pContactCode) {
            return base.Channel.ContactFindByCode(pUsername, pPassword, pContactCode);
        }
        
        public string ContactFindByMobile(string pUsername, string pPassword, string pMobile) {
            return base.Channel.ContactFindByMobile(pUsername, pPassword, pMobile);
        }
        
        public string GetAuthorizationTicket(string pUsername, string pPassword) {
            return base.Channel.GetAuthorizationTicket(pUsername, pPassword);
        }
        
        public void Logout(string ticket) {
            base.Channel.Logout(ticket);
        }
        
        public long GetCreditT(out long pCredit, string pTicket) {
            return base.Channel.GetCreditT(out pCredit, pTicket);
        }
        
        public long GetReceivedSmsT(out string pRecieved, string pTicket, bool pWithSchema) {
            return base.Channel.GetReceivedSmsT(out pRecieved, pTicket, pWithSchema);
        }
        
        public long GetReceivedSms2T(out string pRecieved, string pTicket, bool pWithSchema) {
            return base.Channel.GetReceivedSms2T(out pRecieved, pTicket, pWithSchema);
        }
        
        public int GetChargeInfoT(out System.Data.DataTable pReport, string pTicket) {
            return base.Channel.GetChargeInfoT(out pReport, pTicket);
        }
        
        public int GetSmsCostT(out int cost, string pTicket, string sms) {
            return base.Channel.GetSmsCostT(out cost, pTicket, sms);
        }
        
        public long GetSmsNumberPrice(string smsNumber, int basePrice) {
            return base.Channel.GetSmsNumberPrice(smsNumber, basePrice);
        }
        
        public long GetSmsNumberPrice2(string fixPart, string varPart, double ceilPrice, double floorPrice) {
            return base.Channel.GetSmsNumberPrice2(fixPart, varPart, ceilPrice, floorPrice);
        }
        
        public byte GetSectionCount(string body) {
            return base.Channel.GetSectionCount(body);
        }
    }
}
