//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTS.Clock.Business.NotificationServices.WSSmsWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSSmsWebService.ISmsWebService")]
    public interface ISmsWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsWebService/SendKartablSmss", ReplyAction="http://tempuri.org/ISmsWebService/SendKartablSmssResponse")]
        void SendKartablSmss(GTS.Clock.Infrastructure.InfoServiceProxy[] readyForSendSms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsWebService/SendRequestSmss", ReplyAction="http://tempuri.org/ISmsWebService/SendRequestSmssResponse")]
        void SendRequestSmss(GTS.Clock.Infrastructure.InfoServiceProxy[] readyForSendSms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsWebService/SendTrafficSmss", ReplyAction="http://tempuri.org/ISmsWebService/SendTrafficSmssResponse")]
        void SendTrafficSmss(GTS.Clock.Infrastructure.InfoServiceProxy[] readyForSendSms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsWebService/GetAllSmsSettings", ReplyAction="http://tempuri.org/ISmsWebService/GetAllSmsSettingsResponse")]
        GTS.Clock.Infrastructure.InfoServiceProxy[] GetAllSmsSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsWebService/RunSmsServices", ReplyAction="http://tempuri.org/ISmsWebService/RunSmsServicesResponse")]
        void RunSmsServices(GTS.Clock.Infrastructure.InfoServiceProxy[] readyForSendSms);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmsWebServiceChannel : GTS.Clock.Business.NotificationServices.WSSmsWebService.ISmsWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsWebServiceClient : System.ServiceModel.ClientBase<GTS.Clock.Business.NotificationServices.WSSmsWebService.ISmsWebService>, GTS.Clock.Business.NotificationServices.WSSmsWebService.ISmsWebService {
        
        public SmsWebServiceClient() {
        }
        
        public SmsWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendKartablSmss(GTS.Clock.Infrastructure.InfoServiceProxy[] readyForSendSms) {
            base.Channel.SendKartablSmss(readyForSendSms);
        }
        
        public void SendRequestSmss(GTS.Clock.Infrastructure.InfoServiceProxy[] readyForSendSms) {
            base.Channel.SendRequestSmss(readyForSendSms);
        }
        
        public void SendTrafficSmss(GTS.Clock.Infrastructure.InfoServiceProxy[] readyForSendSms) {
            base.Channel.SendTrafficSmss(readyForSendSms);
        }
        
        public GTS.Clock.Infrastructure.InfoServiceProxy[] GetAllSmsSettings() {
            return base.Channel.GetAllSmsSettings();
        }
        
        public void RunSmsServices(GTS.Clock.Infrastructure.InfoServiceProxy[] readyForSendSms) {
            base.Channel.RunSmsServices(readyForSendSms);
        }
    }
}
