//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Login {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Login.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string alignObj_align {
            get {
                return ResourceManager.GetString("alignObj.align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hftitle.
        /// </summary>
        internal static string hftitle_Value {
            get {
                return ResourceManager.GetString("hftitle.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string InverseAlignObj_align {
            get {
                return ResourceManager.GetString("InverseAlignObj.align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string lblPassword_Login_Text {
            get {
                return ResourceManager.GetString("lblPassword_Login.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName :.
        /// </summary>
        internal static string lblUserName_Login_Text {
            get {
                return ResourceManager.GetString("lblUserName_Login.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string LoginForm_dir {
            get {
                return ResourceManager.GetString("LoginForm.dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Text {
            get {
                return ResourceManager.GetString("Login.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        internal static string Login_title {
            get {
                return ResourceManager.GetString("Login.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        internal static string PasswordRequired_Text {
            get {
                return ResourceManager.GetString("PasswordRequired.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string RememberMe_Text {
            get {
                return ResourceManager.GetString("RememberMe.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName or Password is Invalid.
        /// </summary>
        internal static string theLogincontrol_FailureText {
            get {
                return ResourceManager.GetString("theLogincontrol.FailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is Required.
        /// </summary>
        internal static string UserNameRequired_Text {
            get {
                return ResourceManager.GetString("UserNameRequired.Text", resourceCulture);
            }
        }
    }
}
