//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MainPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MainPage.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string AlignObj_align {
            get {
                return ResourceManager.GetString("AlignObj.align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab_left_icon.gif.
        /// </summary>
        internal static string DefaultTabLook_LeftIconUrl {
            get {
                return ResourceManager.GetString("DefaultTabLook.LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab_right_icon.gif.
        /// </summary>
        internal static string DefaultTabLook_RightIconUrl {
            get {
                return ResourceManager.GetString("DefaultTabLook.RightIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartable.
        /// </summary>
        internal static string hfdmItemCartable_DockMenu_Value {
            get {
                return ResourceManager.GetString("hfdmItemCartable_DockMenu.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Operation Manager Report.
        /// </summary>
        internal static string hfdmItemManagerMasterMonthlyOperationReport_DockMenu_Value {
            get {
                return ResourceManager.GetString("hfdmItemManagerMasterMonthlyOperationReport_DockMenu.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Introduction.
        /// </summary>
        internal static string hfdmItemPersonnelIntroduction_DockMenu_Value {
            get {
                return ResourceManager.GetString("hfdmItemPersonnelIntroduction_DockMenu.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Operation Report.
        /// </summary>
        internal static string hfdmItemPersonnelMasterMonthlyOperationReport_DockMenu_Value {
            get {
                return ResourceManager.GetString("hfdmItemPersonnelMasterMonthlyOperationReport_DockMenu.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Requests.
        /// </summary>
        internal static string hfdmItemRegisteredRequests_DockMenu_Value {
            get {
                return ResourceManager.GetString("hfdmItemRegisteredRequests_DockMenu.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Introduction.
        /// </summary>
        internal static string hfdmItemReportsIntroduction_DockMenu_Value {
            get {
                return ResourceManager.GetString("hfdmItemReportsIntroduction_DockMenu.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveyed Requests.
        /// </summary>
        internal static string hfdmItemSurveyedRequests_DockMenu_Value {
            get {
                return ResourceManager.GetString("hfdmItemSurveyedRequests_DockMenu.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Operation By Operator.
        /// </summary>
        internal static string hfdmItemTrafficOperationByOperator_DockMenu_Value {
            get {
                return ResourceManager.GetString("hfdmItemTrafficOperationByOperator_DockMenu.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main View.
        /// </summary>
        internal static string hfdmItemWelcome_DockMenu_Value {
            get {
                return ResourceManager.GetString("hfdmItemWelcome_DockMenu.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Flows Introduction.
        /// </summary>
        internal static string hfdmItemWorkFlowsView_DockMenu_Value {
            get {
                return ResourceManager.GetString("hfdmItemWorkFlowsView_DockMenu.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string imgEnglish_title {
            get {
                return ResourceManager.GetString("imgEnglish.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        internal static string imgPersian_title {
            get {
                return ResourceManager.GetString("imgPersian.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string InverseAlignObj_align {
            get {
                return ResourceManager.GetString("InverseAlignObj.align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2Item_en.
        /// </summary>
        internal static string Level2ItemLook_CssClass {
            get {
                return ResourceManager.GetString("Level2ItemLook.CssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2ItemHover_en.
        /// </summary>
        internal static string Level2ItemLook_HoverCssClass {
            get {
                return ResourceManager.GetString("Level2ItemLook.HoverCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2ItemSelected_en.
        /// </summary>
        internal static string Level2SelectedItemLook_CssClass {
            get {
                return ResourceManager.GetString("Level2SelectedItemLook.CssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2ItemSelected_en.
        /// </summary>
        internal static string Level2SelectedItemLook_HoverCssClass {
            get {
                return ResourceManager.GetString("Level2SelectedItemLook.HoverCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string MainForm_dir {
            get {
                return ResourceManager.GetString("MainForm.dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and Attendance Web Application.
        /// </summary>
        internal static string MainForm_title {
            get {
                return ResourceManager.GetString("MainForm.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavBar_en.
        /// </summary>
        internal static string NavBarMain_CssClass {
            get {
                return ResourceManager.GetString("NavBarMain.CssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string NavBarMain_DefaultItemTextAlign {
            get {
                return ResourceManager.GetString("NavBarMain.DefaultItemTextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Levels.
        /// </summary>
        internal static string nvbItemAccessLevels_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemAccessLevels_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2Group_en.
        /// </summary>
        internal static string nvbItemBasicDefinitions_NavBarMain_SubGroupCssClass {
            get {
                return ResourceManager.GetString("nvbItemBasicDefinitions_NavBarMain.SubGroupCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemCalculationRangeDefinition_NavBarMain.png.
        /// </summary>
        internal static string nvbItemCalculationRangeDefinition_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemCalculationRangeDefinition_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Range Definition.
        /// </summary>
        internal static string nvbItemCalculationRangeDefinition_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemCalculationRangeDefinition_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string nvbItemCalculations_NavBarMain_Look_RightIconUrl {
            get {
                return ResourceManager.GetString("nvbItemCalculations_NavBarMain.Look-RightIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations.
        /// </summary>
        internal static string nvbItemCalculations_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemCalculations_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemCartable_NavBarMain.png.
        /// </summary>
        internal static string nvbItemCartable_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemCartable_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartable.
        /// </summary>
        internal static string nvbItemCartable_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemCartable_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemConceptRuleManagement_NavBarMain.png.
        /// </summary>
        internal static string nvbItemConceptRuleMasterOperation_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemConceptRuleMasterOperation_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepts &amp; Rules Management.
        /// </summary>
        internal static string nvbItemConceptRuleMasterOperation_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemConceptRuleMasterOperation_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemControlStationIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemControlStationIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemControlStationIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Station Introduction.
        /// </summary>
        internal static string nvbItemControlStationIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemControlStationIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemDepartmentsIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemDepartmentsIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemDepartmentsIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments Introduction.
        /// </summary>
        internal static string nvbItemDepartmentsIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemDepartmentsIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemEmployTypesIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemEmployTypesIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemEmployTypesIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employ Types Introduction.
        /// </summary>
        internal static string nvbItemEmployTypesIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemEmployTypesIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemExceptionShiftsIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemExceptionShiftsIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemExceptionShiftsIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Shifts  Introduction.
        /// </summary>
        internal static string nvbItemExceptionShiftsIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemExceptionShiftsIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemExpressionsOperation_NavBarMain.png.
        /// </summary>
        internal static string nvbItemExpressionsOperation_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemExpressionsOperation_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions Management.
        /// </summary>
        internal static string nvbItemExpressionsOperation_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemExpressionsOperation_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemIllnessIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemIllnessIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemIllnessIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illness Introduction.
        /// </summary>
        internal static string nvbItemIllnessIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemIllnessIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemLateralOperations_NavBarMain.png.
        /// </summary>
        internal static string nvbItemLateralOperations_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemLateralOperations_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2Group_en.
        /// </summary>
        internal static string nvbItemLateralOperations_NavBarMain_SubGroupCssClass {
            get {
                return ResourceManager.GetString("nvbItemLateralOperations_NavBarMain.SubGroupCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lateral Operations.
        /// </summary>
        internal static string nvbItemLateralOperations_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemLateralOperations_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemMachineIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemMachineIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemMachineIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Introduction.
        /// </summary>
        internal static string nvbItemMachineIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemMachineIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemManagerMasterMonthlyOperationReport_NavBarMain.png.
        /// </summary>
        internal static string nvbItemManagerMasterMonthlyOperationReport_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemManagerMasterMonthlyOperationReport_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Operation Manager Report.
        /// </summary>
        internal static string nvbItemManagerMasterMonthlyOperationReport_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemManagerMasterMonthlyOperationReport_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemMasterLeaveRemains_NavBarMain.png.
        /// </summary>
        internal static string nvbItemMasterLeaveRemains_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemMasterLeaveRemains_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Remains.
        /// </summary>
        internal static string nvbItemMasterLeaveRemains_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemMasterLeaveRemains_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemMasterManagersIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemMasterManagersIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemMasterManagersIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers View.
        /// </summary>
        internal static string nvbItemMasterManagersIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemMasterManagersIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemWorkFlowsView_NavBarMain.png.
        /// </summary>
        internal static string nvbItemMasterPublicNews_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemMasterPublicNews_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Public News.
        /// </summary>
        internal static string nvbItemMasterPublicNews_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemMasterPublicNews_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemMissionLocationsIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemMissionLocationsIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemMissionLocationsIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Locations Introduction.
        /// </summary>
        internal static string nvbItemMissionLocationsIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemMissionLocationsIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemPasswordChange_NavBarMain.png.
        /// </summary>
        internal static string nvbItemPasswordChange_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemPasswordChange_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change .
        /// </summary>
        internal static string nvbItemPasswordChange_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemPasswordChange_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemPersonnelIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemPersonnelIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemPersonnelIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Introduction.
        /// </summary>
        internal static string nvbItemPersonnelIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemPersonnelIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemPersonnelMasterMonthlyOperationReport_NavBarMain.png.
        /// </summary>
        internal static string nvbItemPersonnelMasterMonthlyOperationReport_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemPersonnelMasterMonthlyOperationReport_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Operation Report.
        /// </summary>
        internal static string nvbItemPersonnelMasterMonthlyOperationReport_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemPersonnelMasterMonthlyOperationReport_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemPersonnelOrganizationFeaturesChange_NavBarMain.png.
        /// </summary>
        internal static string nvbItemPersonnelOrganizationFeaturesChange_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemPersonnelOrganizationFeaturesChange_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Organization Features Change.
        /// </summary>
        internal static string nvbItemPersonnelOrganizationFeaturesChange_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemPersonnelOrganizationFeaturesChange_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemPhysicianIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemPhysicianIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemPhysicianIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician Introduction.
        /// </summary>
        internal static string nvbItemPhysicianIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemPhysicianIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemPostsIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemPostsIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemPostsIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Posts Introduction.
        /// </summary>
        internal static string nvbItemPostsIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemPostsIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemPreCardIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemPreCardIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemPreCardIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreCard Introduction.
        /// </summary>
        internal static string nvbItemPreCardIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemPreCardIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemPresenceAndAbsenceOperation_NavBarMain.png.
        /// </summary>
        internal static string nvbItemPresenceAndAbsenceOperation_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemPresenceAndAbsenceOperation_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2Group_en.
        /// </summary>
        internal static string nvbItemPresenceAndAbsenceOperation_NavBarMain_SubGroupCssClass {
            get {
                return ResourceManager.GetString("nvbItemPresenceAndAbsenceOperation_NavBarMain.SubGroupCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and Attendance Issues.
        /// </summary>
        internal static string nvbItemPresenceAndAbsenceOperation_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemPresenceAndAbsenceOperation_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Messages.
        /// </summary>
        internal static string nvbItemPrivateMessage_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemPrivateMessage_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemRegisteredRequests_NavBarMain.png.
        /// </summary>
        internal static string nvbItemRegisteredRequests_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemRegisteredRequests_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Requests.
        /// </summary>
        internal static string nvbItemRegisteredRequests_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemRegisteredRequests_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report_icon.png.
        /// </summary>
        internal static string nvbItemReportsIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemReportsIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Introduction.
        /// </summary>
        internal static string nvbItemReportsIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemReportsIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.png.
        /// </summary>
        internal static string nvbItemReports_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemReports_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string nvbItemReports_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemReports_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemRolesIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemRolesIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemRolesIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Introduction.
        /// </summary>
        internal static string nvbItemRolesIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemRolesIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemRulesGroupIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemRulesGroupIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemRulesGroupIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules Group Introduction.
        /// </summary>
        internal static string nvbItemRulesGroupIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemRulesGroupIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemBasicDefinitions_NavBarMain.png.
        /// </summary>
        internal static string nvbItemsBasicDefinitions_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemsBasicDefinitions_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Definitions.
        /// </summary>
        internal static string nvbItemsBasicDefinitions_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemsBasicDefinitions_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemShiftIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemShiftIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemShiftIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts Introduction.
        /// </summary>
        internal static string nvbItemShiftIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemShiftIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemSubstituteIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemSubstituteIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemSubstituteIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitute Introduction.
        /// </summary>
        internal static string nvbItemSubstituteIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemSubstituteIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemSurveyedRequests_NavBarMain.png.
        /// </summary>
        internal static string nvbItemSurveyedRequests_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemSurveyedRequests_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveyed Requests.
        /// </summary>
        internal static string nvbItemSurveyedRequests_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemSurveyedRequests_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemTrafficOperationByOperator_NavBarMain.png.
        /// </summary>
        internal static string nvbItemTrafficOperationByOperator_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemTrafficOperationByOperator_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Operation By Operator.
        /// </summary>
        internal static string nvbItemTrafficOperationByOperator_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemTrafficOperationByOperator_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Validation.
        /// </summary>
        internal static string nvbItemUiValidation_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemUiValidation_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemUsersIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemUsersIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemUsersIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Introduction.
        /// </summary>
        internal static string nvbItemUsersIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemUsersIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemWorkFlowsView_NavBarMain.png.
        /// </summary>
        internal static string nvbItemWorkFlowsView_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemWorkFlowsView_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Flows Introduction.
        /// </summary>
        internal static string nvbItemWorkFlowsView_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemWorkFlowsView_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemWorkGroups_NavBarMain.png.
        /// </summary>
        internal static string nvbItemWorkGroups_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemWorkGroups_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkGroups Introduction &amp; Planning.
        /// </summary>
        internal static string nvbItemWorkGroups_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemWorkGroups_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemWorkHeatIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemWorkHeatIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemWorkHeatIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkHeat Introduction.
        /// </summary>
        internal static string nvbItemWorkHeatIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemWorkHeatIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvbItemYearlyHolidaysIntroduction_NavBarMain.png.
        /// </summary>
        internal static string nvbItemYearlyHolidaysIntroduction_NavBarMain_Look_LeftIconUrl {
            get {
                return ResourceManager.GetString("nvbItemYearlyHolidaysIntroduction_NavBarMain.Look-LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly Holidays Introduction.
        /// </summary>
        internal static string nvbItemYearlyHolidaysIntroduction_NavBarMain_Text {
            get {
                return ResourceManager.GetString("nvbItemYearlyHolidaysIntroduction_NavBarMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string RetErrorType {
            get {
                return ResourceManager.GetString("RetErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Identifier :.
        /// </summary>
        internal static string RetFatalErrorIdentifier {
            get {
                return ResourceManager.GetString("RetFatalErrorIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string RetFatalErrorType {
            get {
                return ResourceManager.GetString("RetFatalErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RetSuccessType {
            get {
                return ResourceManager.GetString("RetSuccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected_tab_left_icon.gif.
        /// </summary>
        internal static string SelectedTabLook_LeftIconUrl {
            get {
                return ResourceManager.GetString("SelectedTabLook.LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected_tab_right_icon.gif.
        /// </summary>
        internal static string SelectedTabLook_RightIconUrl {
            get {
                return ResourceManager.GetString("SelectedTabLook.RightIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghadir Design &amp; Processing Corporation.
        /// </summary>
        internal static string tbWelcome_TabStripMenus_Text {
            get {
                return ResourceManager.GetString("tbWelcome_TabStripMenus.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string tlbItemLogout_tlbLogout_Tooltip {
            get {
                return ResourceManager.GetString("tlbItemLogout_tlbLogout.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopItemActive_en.
        /// </summary>
        internal static string TopItemLook_ActiveCssClass {
            get {
                return ResourceManager.GetString("TopItemLook.ActiveCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopItem_en.
        /// </summary>
        internal static string TopItemLook_CssClass {
            get {
                return ResourceManager.GetString("TopItemLook.CssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopItemHover_en.
        /// </summary>
        internal static string TopItemLook_HoverCssClass {
            get {
                return ResourceManager.GetString("TopItemLook.HoverCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Exit.
        /// </summary>
        internal static string UserExit_TopToolbar_Text {
            get {
                return ResourceManager.GetString("UserExit_TopToolbar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;configuration&gt;
        ///  &lt;system.web&gt;
        ///    &lt;authorization &gt;
        ///      &lt;allow users=&quot;*&quot;/&gt;
        ///    &lt;/authorization&gt;
        ///  &lt;/system.web&gt;
        ///
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Time.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
