//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MasterPersonnel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MasterPersonnel.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active_GridPersonnel_Personnel_HeadingText {
            get {
                return ResourceManager.GetString("Active_GridPersonnel_Personnel.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string AlignObj_align {
            get {
                return ResourceManager.GetString("AlignObj.align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Provided.
        /// </summary>
        internal static string AmadeBeKhedmat {
            get {
                return ResourceManager.GetString("AmadeBeKhedmat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CardNumber_GridPersonnel_Personnel_HeadingText {
            get {
                return ResourceManager.GetString("CardNumber_GridPersonnel_Personnel.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military End Card.
        /// </summary>
        internal static string DarayeKartePayanKhedmat {
            get {
                return ResourceManager.GetString("DarayeKartePayanKhedmat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab_left_icon.gif.
        /// </summary>
        internal static string DefaultTabLook_LeftIconUrl {
            get {
                return ResourceManager.GetString("DefaultTabLook.LeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Operation Completed Successfully.
        /// </summary>
        internal static string DeleteComplete {
            get {
                return ResourceManager.GetString("DeleteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department_GridPersonnel_Personnel_HeadingText {
            get {
                return ResourceManager.GetString("Department_GridPersonnel_Personnel.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Family_GridPersonnel_Personnel_HeadingText {
            get {
                return ResourceManager.GetString("Family_GridPersonnel_Personnel.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Inclusive.
        /// </summary>
        internal static string GheireMashmool {
            get {
                return ResourceManager.GetString("GheireMashmool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military During.
        /// </summary>
        internal static string HeineKhedmat {
            get {
                return ResourceManager.GetString("HeineKhedmat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you Exit from Personnel Form ?.
        /// </summary>
        internal static string hfCloseMessage_Personnel_Value {
            get {
                return ResourceManager.GetString("hfCloseMessage_Personnel.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Connection Error.
        /// </summary>
        internal static string hfConnectionError_Personnel_Value {
            get {
                return ResourceManager.GetString("hfConnectionError_Personnel.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you Delete this Personnel ?.
        /// </summary>
        internal static string hfDeleteMessage_Personnel_Value {
            get {
                return ResourceManager.GetString("hfDeleteMessage_Personnel.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string hfDelete_Personnel_Value {
            get {
                return ResourceManager.GetString("hfDelete_Personnel.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string hfErrorType_Personnel_Value {
            get {
                return ResourceManager.GetString("hfErrorType_Personnel.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 0 of 0.
        /// </summary>
        internal static string hffooter_GridPersonnel_Personnel_Value {
            get {
                return ResourceManager.GetString("hffooter_GridPersonnel_Personnel.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel.
        /// </summary>
        internal static string hfheader_Personnel_Personnel_Value {
            get {
                return ResourceManager.GetString("hfheader_Personnel_Personnel.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading .....
        /// </summary>
        internal static string hfloadingPanel_GridPersonnel_Personnel_Value {
            get {
                return ResourceManager.GetString("hfloadingPanel_GridPersonnel_Personnel.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string hfView_Personnel_Value {
            get {
                return ResourceManager.GetString("hfView_Personnel.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string LableAlign_align {
            get {
                return ResourceManager.GetString("LableAlign.align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card ID :.
        /// </summary>
        internal static string lblCardID_QuickSerch_Personnel_Text {
            get {
                return ResourceManager.GetString("lblCardID_QuickSerch_Personnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family :.
        /// </summary>
        internal static string lblFamily_QuickSerch_Personnel_Text {
            get {
                return ResourceManager.GetString("lblFamily_QuickSerch_Personnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        internal static string lblName_QuickSerch_Personnel_Text {
            get {
                return ResourceManager.GetString("lblName_QuickSerch_Personnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Count :.
        /// </summary>
        internal static string lblPersonnelCount_Personnel_Text {
            get {
                return ResourceManager.GetString("lblPersonnelCount_Personnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel ID :.
        /// </summary>
        internal static string lblPersonnelID_QuickSerch_Personnel_Text {
            get {
                return ResourceManager.GetString("lblPersonnelID_QuickSerch_Personnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Term :.
        /// </summary>
        internal static string lblQuickSerch_Personnel_Text {
            get {
                return ResourceManager.GetString("lblQuickSerch_Personnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string MasterPersonnelMainInformationForm_dir {
            get {
                return ResourceManager.GetString("MasterPersonnelMainInformationForm.dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Freedom.
        /// </summary>
        internal static string MoafiatPezeshki {
            get {
                return ResourceManager.GetString("MoafiatPezeshki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Freedom.
        /// </summary>
        internal static string MoafiatTahsili {
            get {
                return ResourceManager.GetString("MoafiatTahsili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bail Freedom.
        /// </summary>
        internal static string MoafiatTakafol {
            get {
                return ResourceManager.GetString("MoafiatTakafol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string Mojarad {
            get {
                return ResourceManager.GetString("Mojarad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        internal static string Motahel {
            get {
                return ResourceManager.GetString("Motahel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorced.
        /// </summary>
        internal static string Motaleghe {
            get {
                return ResourceManager.GetString("Motaleghe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name_GridPersonnel_Personnel_HeadingText {
            get {
                return ResourceManager.GetString("Name_GridPersonnel_Personnel.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Personnel Selected for Delete.
        /// </summary>
        internal static string NoPersonnelSelectedforDelete {
            get {
                return ResourceManager.GetString("NoPersonnelSelectedforDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Post .
        /// </summary>
        internal static string OrganizationPost_GridPersonnel_Personnel_HeadingText {
            get {
                return ResourceManager.GetString("OrganizationPost_GridPersonnel_Personnel.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Personnel Details Exists in database.
        /// </summary>
        internal static string PersonDetailNotExistsInDatabase {
            get {
                return ResourceManager.GetString("PersonDetailNotExistsInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Number.
        /// </summary>
        internal static string PersonnelNumber_GridPersonnel_Personnel_HeadingText {
            get {
                return ResourceManager.GetString("PersonnelNumber_GridPersonnel_Personnel.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string RetErrorType {
            get {
                return ResourceManager.GetString("RetErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Identifier.
        /// </summary>
        internal static string RetFatalErrorIdentifier {
            get {
                return ResourceManager.GetString("RetFatalErrorIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string RetFatalErrorType {
            get {
                return ResourceManager.GetString("RetFatalErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RetSuccessType {
            get {
                return ResourceManager.GetString("RetSuccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string Sayer {
            get {
                return ResourceManager.GetString("Sayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search.
        /// </summary>
        internal static string tbQuickSearch_TabStripQuickSearch_Personnel_Text {
            get {
                return ResourceManager.GetString("tbQuickSearch_TabStripQuickSearch_Personnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20%.
        /// </summary>
        internal static string td_lblPersonnelCount_Personnel_width {
            get {
                return ResourceManager.GetString("td_lblPersonnelCount_Personnel.width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string tlbItemBefore_TlbPaging_GridPersonnel_Personnel_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemBefore_TlbPaging_GridPersonnel_Personnel.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string tlbItemCancel_TlbCancel_Text {
            get {
                return ResourceManager.GetString("tlbItemCancel_TlbCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string tlbItemDelete_TlbPersonnel_Text {
            get {
                return ResourceManager.GetString("tlbItemDelete_TlbPersonnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string tlbItemEdit_TlbPersonnel_Text {
            get {
                return ResourceManager.GetString("tlbItemEdit_TlbPersonnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string tlbItemExit_TlbPersonnel_Text {
            get {
                return ResourceManager.GetString("tlbItemExit_TlbPersonnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string tlbItemFirst_TlbPaging_GridPersonnel_Personnel_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemFirst_TlbPaging_GridPersonnel_Personnel.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Reconstruction.
        /// </summary>
        internal static string tlbItemFormReconstruction_TlbPersonnel_Text {
            get {
                return ResourceManager.GetString("tlbItemFormReconstruction_TlbPersonnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tlbItemHelp_TlbPersonnel_Text {
            get {
                return ResourceManager.GetString("tlbItemHelp_TlbPersonnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string tlbItemLast_TlbPaging_GridPersonnel_Personnel_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemLast_TlbPaging_GridPersonnel_Personnel.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string tlbItemMessage_TlbPersonnel_Text {
            get {
                return ResourceManager.GetString("tlbItemMessage_TlbPersonnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string tlbItemNew_TlbPersonnel_Text {
            get {
                return ResourceManager.GetString("tlbItemNew_TlbPersonnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string tlbItemNext_TlbPaging_GridPersonnel_Personnel_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemNext_TlbPaging_GridPersonnel_Personnel.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string tlbItemOk_TlbOkConfirm_Text {
            get {
                return ResourceManager.GetString("tlbItemOk_TlbOkConfirm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string tlbItemRefresh_TlbPaging_GridPersonnel_Personnel_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemRefresh_TlbPaging_GridPersonnel_Personnel.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string tlbItemRefresh_TlbPersonnelQuickSearch_Text {
            get {
                return ResourceManager.GetString("tlbItemRefresh_TlbPersonnelQuickSearch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search.
        /// </summary>
        internal static string tlbItemSearch_TlbPersonnelQuickSearch_Text {
            get {
                return ResourceManager.GetString("tlbItemSearch_TlbPersonnelQuickSearch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string tlbItemSearch_TlbPersonnel_Text {
            get {
                return ResourceManager.GetString("tlbItemSearch_TlbPersonnel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkGroup.
        /// </summary>
        internal static string WorkGroup_GridPersonnel_Personnel_HeadingText {
            get {
                return ResourceManager.GetString("WorkGroup_GridPersonnel_Personnel.HeadingText", resourceCulture);
            }
        }
    }
}
