//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.OrganizationPosts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OrganizationPosts.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Operation Completed Successfully.
        /// </summary>
        internal static string AddComplete {
            get {
                return ResourceManager.GetString("AddComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string AlignObj_align {
            get {
                return ResourceManager.GetString("AlignObj.align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Operation Completed Successfully.
        /// </summary>
        internal static string DeleteComplete {
            get {
                return ResourceManager.GetString("DeleteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Operation Completed Successfully.
        /// </summary>
        internal static string EditComplete {
            get {
                return ResourceManager.GetString("EditComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string hfAdd_Posts_Value {
            get {
                return ResourceManager.GetString("hfAdd_Posts.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you Exit from Organization Post Form ?.
        /// </summary>
        internal static string hfCloseMessage_Posts_Value {
            get {
                return ResourceManager.GetString("hfCloseMessage_Posts.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Connection Error.
        /// </summary>
        internal static string hfConnectionError_Posts_Value {
            get {
                return ResourceManager.GetString("hfConnectionError_Posts.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you Delete this Organization Post ?.
        /// </summary>
        internal static string hfDeleteMessage_Posts_Value {
            get {
                return ResourceManager.GetString("hfDeleteMessage_Posts.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string hfDelete_Posts_Value {
            get {
                return ResourceManager.GetString("hfDelete_Posts.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string hfEdit_Posts_Value {
            get {
                return ResourceManager.GetString("hfEdit_Posts.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string hfErrorType_Posts_Value {
            get {
                return ResourceManager.GetString("hfErrorType_Posts.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Posts.
        /// </summary>
        internal static string hfheader_Posts_Posts_Value {
            get {
                return ResourceManager.GetString("hfheader_Posts_Posts.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Post Details.
        /// </summary>
        internal static string hfheader_tblPostsDetails_Posts_Value {
            get {
                return ResourceManager.GetString("hfheader_tblPostsDetails_Posts.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading .....
        /// </summary>
        internal static string hfloadingPanel_trvPosts_Post_Value {
            get {
                return ResourceManager.GetString("hfloadingPanel_trvPosts_Post.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string hfView_Posts_Value {
            get {
                return ResourceManager.GetString("hfView_Posts.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InverseAlignObj.
        /// </summary>
        internal static string InverseAlignObj_InnerText {
            get {
                return ResourceManager.GetString("InverseAlignObj.InnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Organization Post Exists with this Identifier.
        /// </summary>
        internal static string ItemNotExist {
            get {
                return ResourceManager.GetString("ItemNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code :.
        /// </summary>
        internal static string lblOrgPostCode_Posts_Text {
            get {
                return ResourceManager.GetString("lblOrgPostCode_Posts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Name :.
        /// </summary>
        internal static string lblOrgPostName_Posts_Text {
            get {
                return ResourceManager.GetString("lblOrgPostName_Posts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Organization Post Selected for Delete.
        /// </summary>
        internal static string NoOrganizationPostSelectedforDelete {
            get {
                return ResourceManager.GetString("NoOrganizationPostSelectedforDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Organization Post Selected for Edit.
        /// </summary>
        internal static string NoOrganizationPostSelectedforEdit {
            get {
                return ResourceManager.GetString("NoOrganizationPostSelectedforEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string OrganizationPostsForm_dir {
            get {
                return ResourceManager.GetString("OrganizationPostsForm.dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Post Code is Duplicated.
        /// </summary>
        internal static string OrganizationUnitCustomCodeRepeated {
            get {
                return ResourceManager.GetString("OrganizationUnitCustomCodeRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Post Name is Duplicated.
        /// </summary>
        internal static string OrganizationUnitNameRepeated {
            get {
                return ResourceManager.GetString("OrganizationUnitNameRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Post Name is Not Valued.
        /// </summary>
        internal static string OrganizationUnitNameRequierd {
            get {
                return ResourceManager.GetString("OrganizationUnitNameRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Organization Post is Not selected.
        /// </summary>
        internal static string OrganizationUnitParentIDRequierd {
            get {
                return ResourceManager.GetString("OrganizationUnitParentIDRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Parent Organization Post Exists with this Identifier.
        /// </summary>
        internal static string OrganizationUnitParentNotExists {
            get {
                return ResourceManager.GetString("OrganizationUnitParentNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Post Root Delete is Illegal.
        /// </summary>
        internal static string OrganizationUnitRootDeleteIllegal {
            get {
                return ResourceManager.GetString("OrganizationUnitRootDeleteIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Units germ Count in database is Invalid.
        /// </summary>
        internal static string OrganizationUnitRootMoreThanOne {
            get {
                return ResourceManager.GetString("OrganizationUnitRootMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this Organization Post  Assigned to Personnel.
        /// </summary>
        internal static string OrganizationUnitUsedByPerson {
            get {
                return ResourceManager.GetString("OrganizationUnitUsedByPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string OrgNode_trvPosts_Post {
            get {
                return ResourceManager.GetString("OrgNode_trvPosts_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem in Parent Organization Post Information Fill.
        /// </summary>
        internal static string ParentNodeFillProblem {
            get {
                return ResourceManager.GetString("ParentNodeFillProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string RetErrorType {
            get {
                return ResourceManager.GetString("RetErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Identifier :.
        /// </summary>
        internal static string RetFatalErrorIdentifier {
            get {
                return ResourceManager.GetString("RetFatalErrorIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string RetFatalErrorType {
            get {
                return ResourceManager.GetString("RetFatalErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RetSuccessType {
            get {
                return ResourceManager.GetString("RetSuccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string tlbItemCancel_TlbCancel_Text {
            get {
                return ResourceManager.GetString("tlbItemCancel_TlbCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string tlbItemCancel_TlbPosts_Text {
            get {
                return ResourceManager.GetString("tlbItemCancel_TlbPosts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string tlbItemDelete_TlbPosts_Text {
            get {
                return ResourceManager.GetString("tlbItemDelete_TlbPosts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string tlbItemEdit_TlbPosts_Text {
            get {
                return ResourceManager.GetString("tlbItemEdit_TlbPosts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string tlbItemExit_TlbPosts_Text {
            get {
                return ResourceManager.GetString("tlbItemExit_TlbPosts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Reconstruction.
        /// </summary>
        internal static string tlbItemFormReconstruction_TlbPosts_Text {
            get {
                return ResourceManager.GetString("tlbItemFormReconstruction_TlbPosts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tlbItemHelp_TlbPosts_Text {
            get {
                return ResourceManager.GetString("tlbItemHelp_TlbPosts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string tlbItemMessage_TlbPosts_Text {
            get {
                return ResourceManager.GetString("tlbItemMessage_TlbPosts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string tlbItemNew_TlbPosts_Text {
            get {
                return ResourceManager.GetString("tlbItemNew_TlbPosts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string tlbItemOk_TlbOkConfirm_Text {
            get {
                return ResourceManager.GetString("tlbItemOk_TlbOkConfirm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string tlbItemRefresh_TlbRefresh_trvPosts_Post_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemRefresh_TlbRefresh_trvPosts_Post.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string tlbItemSave_TlbPosts_Text {
            get {
                return ResourceManager.GetString("tlbItemSave_TlbPosts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/TreeView/LeftLines.
        /// </summary>
        internal static string trvPosts_Post_LineImagesFolderUrl {
            get {
                return ResourceManager.GetString("trvPosts_Post.LineImagesFolderUrl", resourceCulture);
            }
        }
    }
}
