//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Users {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Users.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Operation Completed Successfully.
        /// </summary>
        internal static string AddComplete {
            get {
                return ResourceManager.GetString("AddComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input Search Term.
        /// </summary>
        internal static string AlarmMessage_SearchPersonnel_Users {
            get {
                return ResourceManager.GetString("AlarmMessage_SearchPersonnel_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string AlignObj_align {
            get {
                return ResourceManager.GetString("AlignObj.align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  BarCode.
        /// </summary>
        internal static string clmnBarCode_cmbPersonnel_Users {
            get {
                return ResourceManager.GetString("clmnBarCode_cmbPersonnel_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string clmnFamily_GridUsers_Users_HeadingText {
            get {
                return ResourceManager.GetString("clmnFamily_GridUsers_Users.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name And Family.
        /// </summary>
        internal static string clmnNameAndFamily_GridUsers_Users_HeadingText {
            get {
                return ResourceManager.GetString("clmnNameAndFamily_GridUsers_Users.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Name And Family.
        /// </summary>
        internal static string clmnName_cmbPersonnel_Users {
            get {
                return ResourceManager.GetString("clmnName_cmbPersonnel_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string clmnName_GridUsers_Users_HeadingText {
            get {
                return ResourceManager.GetString("clmnName_GridUsers_Users.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string clmnPassword_GridUsers_Users_HeadingText {
            get {
                return ResourceManager.GetString("clmnPassword_GridUsers_Users.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Number .
        /// </summary>
        internal static string clmnPersonnelBarCode_GridUsers_Users_HeadingText {
            get {
                return ResourceManager.GetString("clmnPersonnelBarCode_GridUsers_Users.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string clmnState_GridUsers_Users_HeadingText {
            get {
                return ResourceManager.GetString("clmnState_GridUsers_Users.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        internal static string clmnUesrRole_GridUsers_Users_HeadingText {
            get {
                return ResourceManager.GetString("clmnUesrRole_GridUsers_Users.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string clmnUserName_GridUsers_Users_HeadingText {
            get {
                return ResourceManager.GetString("clmnUserName_GridUsers_Users.HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Operation Completed Successfully.
        /// </summary>
        internal static string DeleteComplete {
            get {
                return ResourceManager.GetString("DeleteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Operation Completed Successfully.
        /// </summary>
        internal static string EditComplete {
            get {
                return ResourceManager.GetString("EditComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string hfAdd_Users_Value {
            get {
                return ResourceManager.GetString("hfAdd_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCode.
        /// </summary>
        internal static string hfclmnBarCode_cmbPersonnel_Users_Value {
            get {
                return ResourceManager.GetString("hfclmnBarCode_cmbPersonnel_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string hfclmnCardNum_cmbPersonnel_Users_Value {
            get {
                return ResourceManager.GetString("hfclmnCardNum_cmbPersonnel_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and Family.
        /// </summary>
        internal static string hfclmnName_cmbPersonnel_Users_Value {
            get {
                return ResourceManager.GetString("hfclmnName_cmbPersonnel_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you Exit from Users form ?.
        /// </summary>
        internal static string hfCloseMessage_Users_Value {
            get {
                return ResourceManager.GetString("hfCloseMessage_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Connection Error.
        /// </summary>
        internal static string hfConnectionError_Users_Value {
            get {
                return ResourceManager.GetString("hfConnectionError_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you Delete this User ?.
        /// </summary>
        internal static string hfDeleteMessage_Users_Value {
            get {
                return ResourceManager.GetString("hfDeleteMessage_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string hfDelete_Users_Value {
            get {
                return ResourceManager.GetString("hfDelete_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string hfEdit_Users_Value {
            get {
                return ResourceManager.GetString("hfEdit_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string hfErrorType_Users_Value {
            get {
                return ResourceManager.GetString("hfErrorType_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 0 of 0.
        /// </summary>
        internal static string hffooter_GridUsers_Users_Value {
            get {
                return ResourceManager.GetString("hffooter_GridUsers_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Search.
        /// </summary>
        internal static string hfheader_SearchBox_Users_Value {
            get {
                return ResourceManager.GetString("hfheader_SearchBox_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Personnel Select.
        /// </summary>
        internal static string hfheader_SearchByPersonnelBox_Users_Value {
            get {
                return ResourceManager.GetString("hfheader_SearchByPersonnelBox_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  User Detail.
        /// </summary>
        internal static string hfheader_UserDetailBox_Users_Value {
            get {
                return ResourceManager.GetString("hfheader_UserDetailBox_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Users.
        /// </summary>
        internal static string hfheader_UsersBox_Users_Value {
            get {
                return ResourceManager.GetString("hfheader_UsersBox_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  User Search.
        /// </summary>
        internal static string hfheader_UserSearchBox_Users_Value {
            get {
                return ResourceManager.GetString("hfheader_UserSearchBox_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        internal static string hfloadingPanel_GridUsers_Users_Value {
            get {
                return ResourceManager.GetString("hfloadingPanel_GridUsers_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Validation.
        /// </summary>
        internal static string hfTitle_DialogActiveDirectory_Value {
            get {
                return ResourceManager.GetString("hfTitle_DialogActiveDirectory.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string hfView_Users_Value {
            get {
                return ResourceManager.GetString("hfView_Users.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Operation Completed Successfully.
        /// </summary>
        internal static string InsertComplete {
            get {
                return ResourceManager.GetString("InsertComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string InverseAlignObj_align {
            get {
                return ResourceManager.GetString("InverseAlignObj.align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory.
        /// </summary>
        internal static string lblActiveDirValidation_Users_Text {
            get {
                return ResourceManager.GetString("lblActiveDirValidation_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string lblActiveUser_Users_Text {
            get {
                return ResourceManager.GetString("lblActiveUser_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name :.
        /// </summary>
        internal static string lblDomainName_Users_Text {
            get {
                return ResourceManager.GetString("lblDomainName_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain UserName :.
        /// </summary>
        internal static string lblDomainUserName_Users_Text {
            get {
                return ResourceManager.GetString("lblDomainUserName_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Repeat :.
        /// </summary>
        internal static string lblPasswordRepeat_Users_Text {
            get {
                return ResourceManager.GetString("lblPasswordRepeat_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string lblPassword_Users_Text {
            get {
                return ResourceManager.GetString("lblPassword_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel :.
        /// </summary>
        internal static string lblPersonnel_Users_Text {
            get {
                return ResourceManager.GetString("lblPersonnel_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By :.
        /// </summary>
        internal static string lblSearchField_Users_Text {
            get {
                return ResourceManager.GetString("lblSearchField_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Term :.
        /// </summary>
        internal static string lblSearchTerm_Users_Text {
            get {
                return ResourceManager.GetString("lblSearchTerm_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName Introduction :.
        /// </summary>
        internal static string lblUserNameIntroduction_Users_Text {
            get {
                return ResourceManager.GetString("lblUserNameIntroduction_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName :.
        /// </summary>
        internal static string lblUserName_Users_Text {
            get {
                return ResourceManager.GetString("lblUserName_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role :.
        /// </summary>
        internal static string lblUserRole_Users_Text {
            get {
                return ResourceManager.GetString("lblUserRole_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and Family.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Domain is Selected.
        /// </summary>
        internal static string NoDomainSelected {
            get {
                return ResourceManager.GetString("NoDomainSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Person Selected for Edit.
        /// </summary>
        internal static string NoPersonSelectedforEdit {
            get {
                return ResourceManager.GetString("NoPersonSelectedforEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Specified.
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User is Selected for Delete.
        /// </summary>
        internal static string NoUserSelectedforDelete {
            get {
                return ResourceManager.GetString("NoUserSelectedforDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User is Selected for Edit.
        /// </summary>
        internal static string NoUserSelectedforEdit {
            get {
                return ResourceManager.GetString("NoUserSelectedforEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Not Valued.
        /// </summary>
        internal static string PasswordIsNull {
            get {
                return ResourceManager.GetString("PasswordIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordRepeat is Not Valued.
        /// </summary>
        internal static string PasswordRepeatIsNull {
            get {
                return ResourceManager.GetString("PasswordRepeatIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordRepeat Must Equal Password.
        /// </summary>
        internal static string PasswordRepeatNotEqualPassword {
            get {
                return ResourceManager.GetString("PasswordRepeatNotEqualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Not Valid.
        /// </summary>
        internal static string PaswordNotStrong {
            get {
                return ResourceManager.GetString("PaswordNotStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel BarCode.
        /// </summary>
        internal static string PersonCode {
            get {
                return ResourceManager.GetString("PersonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Details Not Exists in Database.
        /// </summary>
        internal static string PersonDetailNotExistsInDatabase {
            get {
                return ResourceManager.GetString("PersonDetailNotExistsInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Person is Not Selected.
        /// </summary>
        internal static string PersonIDIsNull {
            get {
                return ResourceManager.GetString("PersonIDIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string RetErrorType {
            get {
                return ResourceManager.GetString("RetErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Identifier :.
        /// </summary>
        internal static string RetFatalErrorIdentifier {
            get {
                return ResourceManager.GetString("RetFatalErrorIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string RetFatalErrorType {
            get {
                return ResourceManager.GetString("RetFatalErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RetSuccessType {
            get {
                return ResourceManager.GetString("RetSuccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string RetWarningType {
            get {
                return ResourceManager.GetString("RetWarningType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name is Duplicated.
        /// </summary>
        internal static string RolenameReplication {
            get {
                return ResourceManager.GetString("RolenameReplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role is Not Valued.
        /// </summary>
        internal static string RoleNotExists {
            get {
                return ResourceManager.GetString("RoleNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string RolesNode_trvRoles_Roles {
            get {
                return ResourceManager.GetString("RolesNode_trvRoles_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Required Field Not Provided.
        /// </summary>
        internal static string SomeRequiredFieldNotProvided {
            get {
                return ResourceManager.GetString("SomeRequiredFieldNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Levels Information.
        /// </summary>
        internal static string tlbItemAccessLevelsInformation_TlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemAccessLevelsInformation_TlbUsers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory.
        /// </summary>
        internal static string tlbItemActiveDir_TlbActiveDirValidation_Users_Text {
            get {
                return ResourceManager.GetString("tlbItemActiveDir_TlbActiveDirValidation_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        internal static string tlbItemAdvancedSearch_TlbAdvancedSearch_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemAdvancedSearch_TlbAdvancedSearch_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string tlbItemBefore_TlbPaging_GridUsers_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemBefore_TlbPaging_GridUsers_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string tlbItemBefore_TlbPaging_PersonnelSearch_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemBefore_TlbPaging_PersonnelSearch_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string tlbItemCancel_TlbCancelConfirm_Text {
            get {
                return ResourceManager.GetString("tlbItemCancel_TlbCancelConfirm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string tlbItemCancel_TlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemCancel_TlbUsers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Access Levels.
        /// </summary>
        internal static string tlbItemDataAccessLevels_TlbTlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemDataAccessLevels_TlbTlbUsers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string tlbItemDelete_TlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemDelete_TlbUsers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Save.
        /// </summary>
        internal static string tlbItemEditSave_TlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemEditSave_TlbUsers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string tlbItemEdit_TlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemEdit_TlbUsers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Export.
        /// </summary>
        internal static string tlbItemExcelExport_TlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemExcelExport_TlbUsers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string tlbItemExit_TlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemExit_TlbUsers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string tlbItemFirst_TlbPaging_GridUsers_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemFirst_TlbPaging_GridUsers_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string tlbItemFirst_TlbPaging_PersonnelSearch_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemFirst_TlbPaging_PersonnelSearch_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Reconstruction.
        /// </summary>
        internal static string tlbItemFormReconstruction_TlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemFormReconstruction_TlbUsers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tlbItemHelp_TlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemHelp_TlbUsers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string tlbItemLast_TlbPaging_GridUsers_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemLast_TlbPaging_GridUsers_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string tlbItemLast_TlbPaging_PersonnelSearch_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemLast_TlbPaging_PersonnelSearch_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Save.
        /// </summary>
        internal static string tlbItemNewSave_TlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemNewSave_TlbUsers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string tlbItemNew_TlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemNew_TlbUsers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string tlbItemNext_TlbPaging_GridUsers_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemNext_TlbPaging_GridUsers_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string tlbItemNext_TlbPaging_PersonnelSearch_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemNext_TlbPaging_PersonnelSearch_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string tlbItemOk_TlbOkConfirm_Text {
            get {
                return ResourceManager.GetString("tlbItemOk_TlbOkConfirm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string tlbItemRefresh_TlbPaging_GridUsers_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemRefresh_TlbPaging_GridUsers_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string tlbItemRefresh_TlbPaging_PersonnelSearch_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemRefresh_TlbPaging_PersonnelSearch_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string tlbItemRefresh_TlbRefresh_GridUsers_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemRefresh_TlbRefresh_GridUsers_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Introduction.
        /// </summary>
        internal static string tlbItemRolesIntroduction_TlbUsers_Text {
            get {
                return ResourceManager.GetString("tlbItemRolesIntroduction_TlbUsers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string tlbItemSearch_TlbSearchPersonnel_Users_ToolTip {
            get {
                return ResourceManager.GetString("tlbItemSearch_TlbSearchPersonnel_Users.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string tlbItemUserSearch_TlbUserSearch_Users_Text {
            get {
                return ResourceManager.GetString("tlbItemUserSearch_TlbUserSearch_Users.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/TreeView/LeftLines.
        /// </summary>
        internal static string trvUserRole_cmbUserRole_Users_LineImagesFolderUrl {
            get {
                return ResourceManager.GetString("trvUserRole_cmbUserRole_Users.LineImagesFolderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this UserName for this User Role Already Paired to Selected Personnel.
        /// </summary>
        internal static string UserAndRoleAlreadyPaired {
            get {
                return ResourceManager.GetString("UserAndRoleAlreadyPaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password are Not Equal.
        /// </summary>
        internal static string UserConfirmPasswordNotEqual {
            get {
                return ResourceManager.GetString("UserConfirmPasswordNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is Not Valued.
        /// </summary>
        internal static string UsernameNotProvided {
            get {
                return ResourceManager.GetString("UsernameNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is Duplicated.
        /// </summary>
        internal static string UsernameReplication {
            get {
                return ResourceManager.GetString("UsernameReplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Not Valued.
        /// </summary>
        internal static string UserPasswordIsNull {
            get {
                return ResourceManager.GetString("UserPasswordIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel is Not Selected.
        /// </summary>
        internal static string UserPersonIsNotSpecified {
            get {
                return ResourceManager.GetString("UserPersonIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role is Not Selected.
        /// </summary>
        internal static string UserRoleIsNotSpecified {
            get {
                return ResourceManager.GetString("UserRoleIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string UsersForm_dir {
            get {
                return ResourceManager.GetString("UsersForm.dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string WorkSheetName_ExportedData_GridUsers_Users {
            get {
                return ResourceManager.GetString("WorkSheetName_ExportedData_GridUsers_Users", resourceCulture);
            }
        }
    }
}
